import type { AdminBidListItem } from '@/types/admin-bid';

// Mock data for admin bids list
export const adminBidsData: AdminBidListItem[] = [
    {
        projectId: 1,
        projectName: 'E-Commerce Platform Redesign',
        projectStatus: 'Active',
        projectBudget: 45000,
        startDate: '2024-01-15',
        pendingBidsCount: 5,
        respondedBidsCount: 3,
    },
    {
        projectId: 2,
        projectName: 'Mobile Banking App Development',
        projectStatus: 'Active',
        projectBudget: 78000,
        startDate: '2024-02-01',
        pendingBidsCount: 8,
        respondedBidsCount: 2,
    },
    {
        projectId: 3,
        projectName: 'CRM System Integration',
        projectStatus: 'Completed',
        projectBudget: 32000,
        startDate: '2023-11-10',
        pendingBidsCount: 0,
        respondedBidsCount: 6,
    },
    {
        projectId: 4,
        projectName: 'Healthcare Portal Development',
        projectStatus: 'Active',
        projectBudget: 95000,
        startDate: '2024-01-20',
        pendingBidsCount: 12,
        respondedBidsCount: 4,
    },
    {
        projectId: 5,
        projectName: 'Real Estate Management System',
        projectStatus: 'OnHold',
        projectBudget: 56000,
        startDate: '2024-02-15',
        pendingBidsCount: 3,
        respondedBidsCount: 1,
    },
    {
        projectId: 6,
        projectName: 'Social Media Analytics Dashboard',
        projectStatus: 'Active',
        projectBudget: 42000,
        startDate: '2024-01-25',
        pendingBidsCount: 7,
        respondedBidsCount: 5,
    },
    {
        projectId: 7,
        projectName: 'Inventory Management System',
        projectStatus: 'Completed',
        projectBudget: 38000,
        startDate: '2023-12-01',
        pendingBidsCount: 0,
        respondedBidsCount: 8,
    },
    {
        projectId: 8,
        projectName: 'Education Learning Platform',
        projectStatus: 'Active',
        projectBudget: 67000,
        startDate: '2024-02-05',
        pendingBidsCount: 9,
        respondedBidsCount: 3,
    },
    {
        projectId: 9,
        projectName: 'Logistics Tracking System',
        projectStatus: 'Cancelled',
        projectBudget: 28000,
        startDate: '2023-12-15',
        pendingBidsCount: 0,
        respondedBidsCount: 2,
    },
    {
        projectId: 10,
        projectName: 'Restaurant Management App',
        projectStatus: 'Active',
        projectBudget: 34000,
        startDate: '2024-01-30',
        pendingBidsCount: 6,
        respondedBidsCount: 4,
    },
];
